# Schema for the configuration files of the Test module module.
test_module.settings:
  type: config_object
  label: 'Test page configuration'
  mapping:
    text_field:
      type: text_format
      label: 'Text'
